"""i

Revision ID: a23e63738b7a
Revises: e738a76d22a9
Create Date: 2024-08-30 09:56:46.618634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23e63738b7a'
down_revision = 'e738a76d22a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('photographer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_reviews_customer_id_customers')),
    sa.ForeignKeyConstraint(['photographer_id'], ['photographers.id'], name=op.f('fk_reviews_photographer_id_photographers')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photographs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_photographs_customer_id_customers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_photographs_booking_id_bookings'), 'bookings', ['booking_id'], ['id'])
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photographs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_photographs_booking_id_bookings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_photographs_customer_id_customers', 'customers', ['customer_id'], ['id'])
        batch_op.drop_column('booking_id')

    op.drop_table('reviews')
    # ### end Alembic commands ###
